# Generated by Django 4.0.1 on 2022-01-21 22:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medico', '0002_alter_medicos_options_alter_medicos_data_criacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=20)),
                ('territorio', models.CharField(default='Brasil', max_length=20)),
                ('data_criacao', models.DateField(default=datetime.date.today)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='medico.medicos')),
            ],
            options={
                'verbose_name': 'Paciente',
            },
        ),
    ]
