# Generated by Django 4.0.1 on 2022-01-20 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_alter_medicos_options_alter_medicos_data_criacao_and_more'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacientes',
            options={'verbose_name': 'Paciente'},
        ),
        migrations.AddField(
            model_name='pacientes',
            name='medico',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.DO_NOTHING, to='medico.medicos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='cep',
            field=models.CharField(max_length=20),
        ),
    ]
