# Generated by Django 4.0.1 on 2022-01-19 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicos',
            options={'verbose_name': 'Medico'},
        ),
        migrations.AlterField(
            model_name='medicos',
            name='data_criacao',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
